# Generated by Django 5.2 on 2025-05-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
